movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=250)
    details=models.TextField()
    # year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movies

class MovieForm(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','details','image']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

from .forms import MovieForm
from . models import movies
# Create your views h


def index(request):
    movie=movies.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=movies.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})


def add(request):
    if request.method =='POST':
        name=request.POST.get('name',)
        details=request.POST.get('details',)
        image=request.FILES['image']
        movie=movies(name=name,details=details,image=image)
        movie.save()
    return render(request,'add.html')


def update(request,id):
    movie=movies.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request,id):
    if request.method=='POST':
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')









    return render(request,'index.html',context)

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the name">
    <input type="text" name="details" placeholder="Enter the description">
    <input type="file" name="image">
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    you want to delete<br>
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" width="250" height="250">

        </div>
        <div class="col-md-6">
            <h4>{{movie.name}}</h4>

            <h6>{{movie.details}}</h6><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                <img  src="{{i.image.url}}" alt=""  height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>

                    <a href="{% url 'movieapp:detail' i.id %}">Go somewhere</a>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>


    {% endblock %}